[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
board_build.partitions = huge_app.csv
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
test_ignore = *
extra_scripts = 
    pre:scripts/convert_logo.py
    post:scripts/move_esp32_binaries.py



lib_deps =
    bodmer/TFT_eSPI@^2.5.43
    nitek/XPT2046_Bitbang_Slim@^2.0.0
    lvgl/lvgl@^9.1.0
    miguelbalboa/MFRC522@^1.4.11
    bblanchon/ArduinoJson@^7.0.4

build_flags =
    -D USER_SETUP_LOADED=1
    -D ILI9341_2_DRIVER=1
    -D TFT_MISO=12
    -D TFT_MOSI=13
    -D TFT_SCLK=14
    -D TFT_CS=15
    -D TFT_DC=2
    -D TFT_RST=-1
    -D TFT_BL=21
    -D TFT_BACKLIGHT_ON=HIGH
    -D LOAD_GLCD=1
    -D LOAD_FONT2=1
    -D LOAD_FONT4=1
    -D LOAD_GFXFF=1
    -D SMOOTH_FONT=1
    -D SPI_FREQUENCY=55000000
    -D SPI_READ_FREQUENCY=20000000
    -D TOUCH_MOSI=32
    -D TOUCH_MISO=39
    -D TOUCH_CLK=25
    -D TOUCH_CS=33
    -D LV_CONF_SKIP
    -D LV_COLOR_DEPTH=16
    -D LV_USE_TFT_ESPI=1
    -D LV_USE_STDLIB_MALLOC=LV_STDLIB_CLIB
    -D LV_USE_STDLIB_STRING=LV_STDLIB_CLIB
    -D LV_USE_STDLIB_SPRINTF=LV_STDLIB_CLIB
    -D LV_FONT_MONTSERRAT_14=1
    -D LV_FONT_MONTSERRAT_20=1

[env:desktop]
platform = native
test_framework = unity
build_flags =
    -D NATIVE_TEST
build_src_filter = +<*> -<ui/> -<nfc/> -<main.cpp>
lib_deps =
    bblanchon/ArduinoJson@^7.0.4
test_ignore = test_embedded

[env:test_embedded]
extends = env:esp32dev
build_src_filter = +<*> -<main.cpp> -<ui/> -<nfc/>
test_ignore = test_desktop*
test_build_src = true

[env:simulator]
platform = native
extra_scripts = 
    pre:scripts/convert_logo.py
    post:scripts/move_sim_binary.py
build_flags =
    -D USE_SDL2
    -D LV_CONF_SKIP
    -D LV_USE_TFT_ESPI=0
    -D LV_USE_OS=LV_OS_PTHREAD
    -D LV_USE_SDL
    -D LV_SDL_INCLUDE_PATH="\"SDL2/SDL.h\""
    -D LV_USE_STDLIB_MALLOC=LV_STDLIB_BUILTIN
    -D LV_USE_STDLIB_STRING=LV_STDLIB_BUILTIN
    -D LV_USE_STDLIB_SPRINTF=LV_STDLIB_BUILTIN
    -D LV_FONT_MONTSERRAT_14=1
    -D LV_FONT_MONTSERRAT_20=1
    -I/usr/include/SDL2
    -lSDL2
    -ldl
    -lcurl
lib_deps =
    lvgl/lvgl@^9.1.0
    bblanchon/ArduinoJson@^7.0.4
build_src_filter = +<*> -<nfc/> -<serial/> -<power/>
